import { useState, useEffect } from 'react'
const ROJO='#E10600'; const LOGO='/logo.png'
const getM=(t:string)=>{const n=t.toLowerCase();if(n.includes('pecho')||n.includes('press'))return'PECHO';if(n.includes('espalda')||n.includes('remo'))return'ESPALDA';if(n.includes('hombro'))return'HOMBROS';if(n.includes('bicep'))return'BICEPS';if(n.includes('tricep'))return'TRICEPS';if(n.includes('pierna')||n.includes('sentadilla'))return'PIERNAS';return'FORZA'}
export default function App(){
 const [tab,setTab]=useState('rutinas')
 const [rutinas,setRutinas]=useState<any[]>(()=>JSON.parse(localStorage.getItem('r')||'[{"id":1,"nombre":"LUNES PECHO","dia":"Lun","ejercicios":[{"nombre":"Press Banca","peso":"80","reps":"12"}]}]'))
 const [tienda,setTienda]=useState<any[]>(()=>JSON.parse(localStorage.getItem('t')||'[{"id":1,"nombre":"Dieta Volumen","tipo":"dieta","precio":"5000","alias":"forza.mp","activo":true,"stock":true},{"id":2,"nombre":"Whey Socio","tipo":"suplemento","precio":"25000","alias":"socio.mp","activo":true,"stock":false}]'))
 const [clientes,setClientes]=useState<any[]>(()=>JSON.parse(localStorage.getItem('c')||'[{"id":1,"nombre":"Juan Perez","peso":"80kg","talla":"M","activo":true,"ingreso":"14/09/2026","tAct":"4 dias","tInac":"0 dias","pro":true,"hasta":"30/09/2026","debito":true}]'))
 const [alias,setAlias]=useState(localStorage.getItem('a')||'forza.mp'); const [precio,setPrecio]=useState(localStorage.getItem('p')||'4990')
 const [nR,setNR]=useState(''); const [nE,setNE]=useState(''); const [nD,setND]=useState('Lun'); const [nProd,setNProd]=useState(''); const [nTipo,setNTipo]=useState('suplemento')
 useEffect(()=>localStorage.setItem('r',JSON.stringify(rutinas)),[rutinas]); useEffect(()=>localStorage.setItem('t',JSON.stringify(tienda)),[tienda]); useEffect(()=>localStorage.setItem('c',JSON.stringify(clientes)),[clientes]); useEffect(()=>{localStorage.setItem('a',alias);localStorage.setItem('p',precio)},[alias,precio])
 return(
 <div style={{background:'#0A0A0A',minHeight:'100vh',color:'white',maxWidth:440,margin:'0 auto',paddingBottom:80,fontFamily:'system-ui'}}>
  <div style={{padding:10,background:'#000',borderBottom:`3px solid ${ROJO}`,display:'flex',gap:10,alignItems:'center',position:'sticky',top:0,zIndex:20}}>
   <div style={{width:50,height:50,background:'#fff',borderRadius:12,overflow:'hidden',border:`2px solid ${ROJO}`}}><img src={LOGO} style={{width:'100%',height:'100%',objectFit:'contain'}} onError={e=>{ (e.target as any).style.display='none'}}/></div>
   <b>FORZA <span style={{color:ROJO}}>GYM PRO</span></b>
  </div>
  {tab==='rutinas'&&<div style={{padding:12}}>
   <div style={{background:ROJO,padding:12,borderRadius:12,display:'flex',justifyContent:'space-between'}}><div><div style={{fontSize:9}}>HOY TE TOCA</div><b>{rutinas[0]?.nombre}</b></div><button onClick={()=>Notification.requestPermission()} style={{background:'#fff',border:'none',borderRadius:20,padding:'6px 12px',fontWeight:900,fontSize:10}}>ALARMA</button></div>
   <div style={{marginTop:10,background:'#111',padding:10,borderRadius:12,border:'1px solid #222'}}><input value={nR} onChange={e=>setNR(e.target.value)} placeholder="LUNES PECHO" style={{width:'100%',background:'#000',border:'1px solid #333',color:'#fff',padding:8,borderRadius:8}}/><div style={{display:'flex',gap:5,marginTop:5}}><input value={nE} onChange={e=>setNE(e.target.value)} placeholder="Press Banca" style={{flex:1,background:'#000',border:'1px solid #333',color:'#fff',padding:8,borderRadius:8}}/><select value={nD} onChange={e=>setND(e.target.value)} style={{background:'#000',color:'#fff',borderRadius:8}}><option>Lun</option><option>Mar</option><option>Mie</option><option>Jue</option><option>Vie</option></select><button onClick={()=>{if(!nR||!nE)return;setRutinas([...rutinas,{id:Date.now(),nombre:nR.toUpperCase(),dia:nD,ejercicios:[{nombre:nE,peso:'80',reps:'12'}]}]);setNR('');setNE('')}} style={{background:ROJO,border:'none',color:'#fff',padding:'0 14px',borderRadius:8}}>+</button></div></div>
   {rutinas.map(r=><div key={r.id} style={{marginTop:10,background:'#111',borderRadius:12,border:'1px solid #222'}}><div style={{padding:10,display:'flex',justifyContent:'space-between'}}><b style={{fontSize:12}}>{r.nombre} {r.dia}</b><button onClick={()=>setRutinas(rutinas.filter(x=>x.id!==r.id))} style={{background:'none',border:'none',color:'#666',fontSize:10}}>Borrar</button></div>{r.ejercicios.map((e:any,i:number)=><div key={i} style={{display:'flex',gap:10,padding:10,borderTop:'1px solid #222',alignItems:'center'}}><div style={{width:70,height:70,background:ROJO,borderRadius:10,display:'flex',alignItems:'center',justifyContent:'center',fontWeight:900,fontSize:11}}>{getM(e.nombre)}</div><div><b>{e.nombre.toUpperCase()}</b><div style={{fontSize:10,color:ROJO}}>● {getM(e.nombre)}</div></div></div>)}</div>)}
  </div>}
  {tab==='tienda'&&<div style={{padding:12}}><div style={{display:'flex',gap:5}}><input value={nProd} onChange={e=>setNProd(e.target.value)} placeholder="Producto" style={{flex:1,background:'#000',border:'1px solid #333',color:'#fff',padding:8,borderRadius:8}}/><select value={nTipo} onChange={e=>setNTipo(e.target.value)} style={{background:'#000',color:'#fff',borderRadius:8}}><option value="dieta">dieta</option><option value="suplemento">suplemento</option><option value="indumentaria">indumentaria</option><option value="elemento">elemento</option></select><button onClick={()=>{if(!nProd)return;setTienda([...tienda,{id:Date.now(),nombre:nProd,tipo:nTipo,precio:'5000',alias,activo:true,stock:true}]);setNProd('')}} style={{background:ROJO,border:'none',color:'#fff',borderRadius:8,padding:'0 10px'}}>+</button></div>{tienda.map(p=><div key={p.id} style={{marginTop:8,background:'#111',padding:10,borderRadius:10,border:'1px solid #222',display:'flex',justifyContent:'space-between'}}><div><b style={{fontSize:12}}>{p.nombre}</b><div style={{fontSize:10,color:ROJO}}>{p.tipo} ${p.precio} MP {p.alias} {p.stock?'CON STOCK':'SIN STOCK'}</div></div><button onClick={()=>setTienda(tienda.map(x=>x.id===p.id?{...x,activo:!x.activo}:x))} style={{background:p.activo?ROJO:'#333',border:'none',color:'#fff',borderRadius:20,padding:'4px 10px',fontSize:10}}>{p.activo?'ACTIVO':'OFF'}</button></div>)}</div>}
  {tab==='admin'&&<div style={{padding:12}}><input value={alias} onChange={e=>setAlias(e.target.value)} placeholder="alias MP" style={{width:'100%',background:'#000',border:'1px solid #333',color:'#fff',padding:8,borderRadius:8}}/><input value={precio} onChange={e=>setPrecio(e.target.value)} placeholder="precio PRO" style={{width:'100%',marginTop:5,background:'#000',border:'1px solid #333',color:'#fff',padding:8,borderRadius:8}}/>{clientes.map(c=><div key={c.id} style={{marginTop:8,background:'#111',padding:10,borderRadius:10,borderLeft:`4px solid ${c.activo?ROJO:'#333'}`}}><div style={{display:'flex',justifyContent:'space-between'}}><b>{c.nombre} {c.pro?'PRO':''}</b><button onClick={()=>setClientes(clientes.map(x=>x.id===c.id?{...x,activo:!x.activo}:x))} style={{fontSize:10,background:'#000',color:'#fff',border:'1px solid #333',borderRadius:8}}>{c.activo?'ACTIVO':'INACTIVO'}</button></div><div style={{fontSize:10,opacity:0.6}}>{c.peso} {c.talla} Act:{c.tAct} Inac:{c.tInac} Ing:{c.ingreso} Hasta:{c.hasta}</div><div style={{display:'flex',gap:5,marginTop:5}}><button style={{fontSize:10,background:ROJO,border:'none',color:'#fff',padding:'4px 8px',borderRadius:8}}>Ver fotos</button><button onClick={()=>setClientes(clientes.map(x=>x.id===c.id?{...x,pro:!x.pro}:x))} style={{fontSize:10,background:'#222',color:'#fff',border:'1px solid #333',borderRadius:8}}>{c.pro?'Quitar PRO':'Dar PRO'}</button></div></div>)}</div>}
  {tab==='planes'&&<div style={{padding:12}}><div style={{background:'#111',padding:12,borderRadius:12,border:'1px solid #333'}}><b>GRATIS $0</b></div><div style={{marginTop:8,background:'#1a0505',padding:12,borderRadius:12,border:`2px solid ${ROJO}`}}><b>PRO ${precio}</b><div style={{fontSize:11}}>MP {alias} • Débito auto</div></div></div>}
  <div style={{position:'fixed',bottom:0,left:0,right:0,maxWidth:440,margin:'0 auto',background:'#000',borderTop:'1px solid #222',display:'flex',justifyContent:'space-around',padding:'10px 0'}}>{['rutinas','tienda','admin','planes'].map(t=><button key={t} onClick={()=>setTab(t)} style={{background:'none',border:'none',color:tab===t?ROJO:'#555',fontSize:10,fontWeight:900}}>{t.toUpperCase()}</button>)}</div>
 </div>
)
}
